# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1209, 857)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.RackSelection = RackButtons(self.centralwidget)
        self.RackSelection.setGeometry(QtCore.QRect(700, 500, 441, 201))
        self.RackSelection.setObjectName("RackSelection")
        self.RackStatusDisplay = RackStatus(self.centralwidget)
        self.RackStatusDisplay.setGeometry(QtCore.QRect(700, 210, 441, 261))
        self.RackStatusDisplay.setObjectName("RackStatusDisplay")
        self.LoadButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadButton.setGeometry(QtCore.QRect(280, 560, 151, 91))
        self.LoadButton.setObjectName("LoadButton")
        self.CentStatusDisplay = CentStatus(self.centralwidget)
        self.CentStatusDisplay.setGeometry(QtCore.QRect(150, 150, 451, 311))
        self.CentStatusDisplay.setObjectName("CentStatusDisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1209, 21))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSetup = QtWidgets.QAction(MainWindow)
        self.actionSetup.setObjectName("actionSetup")
        self.menuOptions.addAction(self.actionSetup)
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Centrifuge Controls 9000"))
        self.LoadButton.setText(_translate("MainWindow", "Load"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionSetup.setText(_translate("MainWindow", "Setup"))
from frontend.customWidgets import CentStatus, RackButtons, RackStatus


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
